name: Deploy Staging
on:
  push:
    branches: 
      - master

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master    

      - name: Build
        uses: ./.github/actions/build
  
  deploy:
    name: Deploy Staging
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: "Checkout"
        uses: actions/checkout@master  

      - name: Deploy
        uses: ./.github/actions/deploy

