name: Deploy Production
on:
  release:
    types: [published]

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master    

      - name: Build
        uses: ./.github/actions/build
  
  deploy:
    name: Deploy Production
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: production-approver
    steps:
      - name: "Checkout"
        uses: actions/checkout@master  

      - name: Deploy
        uses: ./.github/actions/deploy
