name: Pull Request
on:
  pull_request:
    branches: 
      - master

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@master    

      - name: Build
        uses: ./.github/actions/build